from __future__ import annotations

from autograde.coverage.aspect_model import CriterionAspect
from autograde.rubric import Criterion, Rubric, ScoringPolicy


def humanities_short_answer_template(assignment_id: str, assignment_title: str) -> Rubric:
    return Rubric(
        assignment_id=assignment_id,
        assignment_title=assignment_title,
        required_artifacts=["text"],
        criteria=[
            Criterion(
                criterion_id="H1",
                name="Prompt relevance and core point coverage",
                description="Assess whether the response addresses the question and covers the central expected ideas.",
                max_score=40,
                weight=0.40,
                required_modalities=["text"],
                evaluation_dimensions=["clarity", "completeness"],
                evaluator_hints=["prompt_relevance", "subjective_answer_quality", "llm_subjective_reasoning"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="review_only",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="answer_present",
                        description="A substantive answer is present.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                        min_evidence_count=1,
                    ),
                    CriterionAspect(
                        aspect_id="core_points_present",
                        description="The response addresses the expected core points of the question.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, 
                    "length_band": "short",
                    "prompt_terms": ["question", "answer", "argument", "claim"],
                    "expected_concepts": [
                        {"name": "main claim", "synonyms": ["argument", "position", "point"], "required": True},
                        {"name": "support", "synonyms": ["reason", "because", "evidence", "example"], "required": True},
                        {"name": "qualification", "synonyms": ["however", "limitation", "counter", "although"], "required": False},
                    ],
                },
            ),
            Criterion(
                criterion_id="H2",
                name="Justification and quality of reasoning",
                description="Assess whether the response gives reasons, examples, or textual support rather than only assertions.",
                max_score=35,
                weight=0.35,
                required_modalities=["text"],
                evaluation_dimensions=["coherence", "justification"],
                evaluator_hints=["argumentation", "subjective_answer_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="review_only",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="reasoning_visible",
                        description="The response contains visible reasoning or explanation.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, 
                    "length_band": "short",
                    "prompt_terms": ["because", "reason", "example", "support"],
                    "expected_concepts": [
                        {"name": "reason", "synonyms": ["because", "therefore", "thus", "hence"], "required": True},
                        {"name": "example", "synonyms": ["for example", "for instance", "case"], "required": False},
                    ],
                },
            ),
            Criterion(
                criterion_id="H3",
                name="Expression and concision",
                description="Assess whether the answer is readable, appropriately concise, and focused on the question.",
                max_score=25,
                weight=0.25,
                required_modalities=["text"],
                evaluation_dimensions=["clarity", "organization"],
                evaluator_hints=["text_quality", "discourse_structure", "subjective_answer_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="ignore",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="focused_response",
                        description="The answer remains focused rather than drifting away from the prompt.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, "length_band": "short"},
            ),
        ],
        normalize_to=100.0,
    )


def humanities_essay_template(assignment_id: str, assignment_title: str) -> Rubric:
    return Rubric(
        assignment_id=assignment_id,
        assignment_title=assignment_title,
        required_artifacts=["text"],
        criteria=[
            Criterion(
                criterion_id="E1",
                name="Thesis and interpretive position",
                description="Assess whether the essay presents a clear thesis or interpretive position relevant to the prompt.",
                max_score=20,
                weight=0.20,
                required_modalities=["text"],
                evaluation_dimensions=["clarity", "coherence"],
                evaluator_hints=["thesis_strength", "prompt_relevance", "subjective_answer_quality", "llm_argument_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="review_only",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="thesis_present",
                        description="The essay states a clear claim or interpretive thesis.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, 
                    "length_band": "long",
                    "prompt_terms": ["thesis", "interpretation", "argument", "essay"],
                    "expected_concepts": [
                        {"name": "thesis", "synonyms": ["argue", "claim", "position", "contend"], "required": True},
                        {"name": "interpretation", "synonyms": ["suggests", "implies", "reveals", "shows"], "required": True},
                    ],
                },
            ),
            Criterion(
                criterion_id="E2",
                name="Argument development and reasoning",
                description="Assess whether the essay develops its position with connected reasoning and qualification where needed.",
                max_score=30,
                weight=0.30,
                required_modalities=["text"],
                evaluation_dimensions=["coherence", "justification", "organization"],
                evaluator_hints=["argumentation", "counterargument_awareness", "interpretive_depth", "subjective_answer_quality", "llm_argument_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="review_only",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="reasoning_chain",
                        description="The essay develops reasons rather than making isolated assertions.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                    CriterionAspect(
                        aspect_id="qualification_or_nuance",
                        description="The essay acknowledges complexity, qualification, or counter-considerations.",
                        required=False,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, 
                    "length_band": "long",
                    "prompt_terms": ["argument", "however", "because", "analysis"],
                    "expected_concepts": [
                        {"name": "reasoning", "synonyms": ["because", "therefore", "thus", "hence", "this suggests"], "required": True},
                        {"name": "nuance", "synonyms": ["however", "although", "while", "yet", "on the other hand"], "required": False},
                    ],
                },
            ),
            Criterion(
                criterion_id="E3",
                name="Use of textual or source evidence",
                description="Assess whether claims are supported with quotations, references, or source-based evidence when appropriate.",
                max_score=25,
                weight=0.25,
                required_modalities=["text"],
                evaluation_dimensions=["citation_quality", "justification"],
                evaluator_hints=["citation_integrity", "textual_evidence_usage", "source_integration", "subjective_answer_quality", "llm_argument_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="discount_if_relevant",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="evidence_present",
                        description="The essay uses source evidence or references to support major claims.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                    ),
                ],
                metadata={"llm_weight": 0.2, 
                    "length_band": "long",
                    "prompt_terms": ["evidence", "text", "author", "quotation"],
                    "expected_concepts": [
                        {"name": "source evidence", "synonyms": ["according", "quote", "quoted", "author", "text", "passage"], "required": True},
                    ],
                },
            ),
            Criterion(
                criterion_id="E4",
                name="Writing quality and structure",
                description="Assess readability, organization, and whether the essay holds together as a coherent whole.",
                max_score=25,
                weight=0.25,
                required_modalities=["text"],
                evaluation_dimensions=["clarity", "organization"],
                evaluator_hints=["text_quality", "discourse_structure", "subjective_answer_quality"],
                artifact_scope=["text", "report"],
                scoring_policy=ScoringPolicy(mode="weighted_average"),
                integrity_policy="ignore",
                integrity_scope="text",
                aspects=[
                    CriterionAspect(
                        aspect_id="multi_paragraph_structure",
                        description="The essay contains a developed multi-part response.",
                        required=True,
                        modalities=["text"],
                        evidence_types=["paragraph"],
                        min_evidence_count=2,
                    ),
                ],
                metadata={"llm_weight": 0.2, "length_band": "long"},
            ),
        ],
        normalize_to=100.0,
    )
