from __future__ import annotations

from autograde.evaluators.core import (
    ArgumentationEvaluator,
    BehavioralCorrectnessEvaluator,
    CitationIntegrityEvaluator,
    CodeQualityEvaluator,
    CrossModalConsistencyEvaluator,
    DesignFunctionalPlausibilityEvaluator,
    TopologyConstraintSatisfactionEvaluator,
    AlternativeDesignPlausibilityEvaluator,
    BehavioralMetricAlignmentEvaluator,
    DesignReportAlignmentEvaluator,
    DerivationStepQualityEvaluator,
    DiscourseStructureEvaluator,
    PromptRelevanceEvaluator,
    CounterargumentAwarenessEvaluator,
    SourceIntegrationEvaluator,
    InterpretiveDepthEvaluator,
    DiagramCompletenessEvaluator,
    ImplementationReportAlignmentEvaluator,
    ProofValidityEvaluator,
    RequirementsCoverageEvaluator,
    TheoremDefinitionUseEvaluator,
    ConclusionTargetAlignmentEvaluator,
    ResultAnalysisEvaluator,
    SimulationConsistencyEvaluator,
    SimulationEvidenceEvaluator,
    LabSetupCompletenessEvaluator,
    ObservationTableQualityEvaluator,
    CalculationCorrectnessEvaluator,
    MeasuredExpectedAlignmentEvaluator,
    ErrorAnalysisQualityEvaluator,
    SimulationHardwareAlignmentEvaluator,
    WaveformInterpretationEvaluator,
    SpectrumMetricAlignmentEvaluator,
    TimingDiagramCorrectnessEvaluator,
    HDLBehaviorConsistencyEvaluator,
    ExpectedVsSimulatedBehaviorEvaluator,
    DigitalTruthTableConsistencyEvaluator,
    HardwareSoftwareAlignmentEvaluator,
    PeripheralConfigurationCorrectnessEvaluator,
    SensorActuatorBehaviorEvaluator,
    SerialLogBehaviorAlignmentEvaluator,
    StateMachineBehaviorEvaluator,
    PlotInterpretationEvaluator,
    ObservationSheetUnderstandingEvaluator,
    SubjectiveAnswerQualityEvaluator,
    TechnicalCorrectnessEvaluator,
    TextQualityEvaluator,
    TextualEvidenceUsageEvaluator,
    ThesisStrengthEvaluator,
)
from autograde.evaluators.types import DeterministicEvaluator, HybridEvaluator, LLMEvaluator
from autograde.llm.evaluators import (
    LLMArgumentQualityEvaluator,
    LLMDesignJustificationEvaluator,
    LLMFeedbackSynthesizerEvaluator,
    LLMProofExplanationEvaluator,
    LLMSubjectiveReasoningEvaluator,
)


class EvaluatorRegistry:
    """Registry exposing only three evaluator kinds: deterministic, llm, and hybrid."""

    def __init__(self) -> None:
        self._registry = {
            "requirements_coverage": DeterministicEvaluator("requirements_coverage", "requirements_coverage", RequirementsCoverageEvaluator(), notes="Uses explicit rubric requirements."),
            "text_quality": DeterministicEvaluator("text_quality", "text_quality", TextQualityEvaluator(), heuristic=True),
            "argumentation": DeterministicEvaluator("argumentation", "argumentation", ArgumentationEvaluator(), heuristic=True),
            "subjective_answer_quality": HybridEvaluator("subjective_answer_quality", "subjective_answer_quality", SubjectiveAnswerQualityEvaluator(), LLMSubjectiveReasoningEvaluator(), llm_weight=0.2, notes="Preferred for subjective responses."),
            "code_quality": DeterministicEvaluator("code_quality", "code_quality", CodeQualityEvaluator(), heuristic=True),
            "behavioral_correctness": DeterministicEvaluator("behavioral_correctness", "behavioral_correctness", BehavioralCorrectnessEvaluator(), notes="Execution evidence dominates."),
            "implementation_report_alignment": HybridEvaluator("implementation_report_alignment", "implementation_report_alignment", ImplementationReportAlignmentEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.15),
            "diagram_completeness": DeterministicEvaluator("diagram_completeness", "diagram_completeness", DiagramCompletenessEvaluator(), heuristic=True),
            "design_functional_plausibility": HybridEvaluator("design_functional_plausibility", "design_functional_plausibility", DesignFunctionalPlausibilityEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.2),
            "topology_constraint_satisfaction": DeterministicEvaluator("topology_constraint_satisfaction", "topology_constraint_satisfaction", TopologyConstraintSatisfactionEvaluator(), heuristic=True, notes="Checks engineering topology constraints instead of exact diagram matching."),
            "alternative_design_plausibility": HybridEvaluator("alternative_design_plausibility", "alternative_design_plausibility", AlternativeDesignPlausibilityEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.2, notes="Rewards plausible non-unique designs when supported by rationale/evidence."),
            "behavioral_metric_alignment": DeterministicEvaluator("behavioral_metric_alignment", "behavioral_metric_alignment", BehavioralMetricAlignmentEvaluator(), heuristic=True, notes="Checks whether observed metrics and target behavior align."),
            "design_report_alignment": HybridEvaluator("design_report_alignment", "design_report_alignment", DesignReportAlignmentEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.15),
            "simulation_evidence": DeterministicEvaluator("simulation_evidence", "simulation_evidence", SimulationEvidenceEvaluator(), heuristic=True),
            "technical_correctness": DeterministicEvaluator("technical_correctness", "technical_correctness", TechnicalCorrectnessEvaluator(), heuristic=True),
            "cross_modal_consistency": DeterministicEvaluator("cross_modal_consistency", "cross_modal_consistency", CrossModalConsistencyEvaluator(), heuristic=True),
            "citation_integrity": DeterministicEvaluator("citation_integrity", "citation_integrity", CitationIntegrityEvaluator(), heuristic=True),
            "thesis_strength": HybridEvaluator("thesis_strength", "thesis_strength", ThesisStrengthEvaluator(), LLMArgumentQualityEvaluator(), llm_weight=0.25, notes="Replaces weak thesis-only heuristics with bounded LLM support."),
            "textual_evidence_usage": HybridEvaluator("textual_evidence_usage", "textual_evidence_usage", TextualEvidenceUsageEvaluator(), LLMArgumentQualityEvaluator(), llm_weight=0.2),
            "proof_validity": HybridEvaluator("proof_validity", "proof_validity", ProofValidityEvaluator(), LLMProofExplanationEvaluator(), llm_weight=0.25, notes="Deterministic proof cues alone are insufficient for advanced proofs."),
            "derivation_step_quality": HybridEvaluator("derivation_step_quality", "derivation_step_quality", DerivationStepQualityEvaluator(), LLMProofExplanationEvaluator(), llm_weight=0.2, notes="Focuses on symbolic transitions and step-to-step validity."),
            "theorem_definition_use": DeterministicEvaluator("theorem_definition_use", "theorem_definition_use", TheoremDefinitionUseEvaluator(), heuristic=True, notes="Checks grounding in definitions/lemmas/theorems."),
            "conclusion_target_alignment": DeterministicEvaluator("conclusion_target_alignment", "conclusion_target_alignment", ConclusionTargetAlignmentEvaluator(), heuristic=True, notes="Checks whether final claim aligns with stated goal."),
            "result_analysis": HybridEvaluator("result_analysis", "result_analysis", ResultAnalysisEvaluator(), LLMSubjectiveReasoningEvaluator(), llm_weight=0.2),
            "simulation_consistency": HybridEvaluator("simulation_consistency", "simulation_consistency", SimulationConsistencyEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.2),
            "lab_setup_completeness": DeterministicEvaluator("lab_setup_completeness", "lab_setup_completeness", LabSetupCompletenessEvaluator(), heuristic=True, notes="Checks apparatus/setup completeness for EE/ECE labs."),
            "observation_table_quality": DeterministicEvaluator("observation_table_quality", "observation_table_quality", ObservationTableQualityEvaluator(), heuristic=True),
            "calculation_correctness": DeterministicEvaluator("calculation_correctness", "calculation_correctness", CalculationCorrectnessEvaluator(), heuristic=True),
            "measured_expected_alignment": DeterministicEvaluator("measured_expected_alignment", "measured_expected_alignment", MeasuredExpectedAlignmentEvaluator(), heuristic=True),
            "error_analysis_quality": HybridEvaluator("error_analysis_quality", "error_analysis_quality", ErrorAnalysisQualityEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.15),
            "simulation_hardware_alignment": HybridEvaluator("simulation_hardware_alignment", "simulation_hardware_alignment", SimulationHardwareAlignmentEvaluator(), LLMDesignJustificationEvaluator(), llm_weight=0.15),
            "waveform_interpretation": DeterministicEvaluator("waveform_interpretation", "waveform_interpretation", WaveformInterpretationEvaluator(), heuristic=True),
            "spectrum_metric_alignment": DeterministicEvaluator("spectrum_metric_alignment", "spectrum_metric_alignment", SpectrumMetricAlignmentEvaluator(), heuristic=True),
            "timing_diagram_correctness": DeterministicEvaluator("timing_diagram_correctness", "timing_diagram_correctness", TimingDiagramCorrectnessEvaluator(), heuristic=True),
            "hdl_behavior_consistency": DeterministicEvaluator("hdl_behavior_consistency", "hdl_behavior_consistency", HDLBehaviorConsistencyEvaluator(), heuristic=True),
            "expected_vs_simulated_behavior": DeterministicEvaluator("expected_vs_simulated_behavior", "expected_vs_simulated_behavior", ExpectedVsSimulatedBehaviorEvaluator(), heuristic=True),
            "digital_truth_table_consistency": DeterministicEvaluator("digital_truth_table_consistency", "digital_truth_table_consistency", DigitalTruthTableConsistencyEvaluator(), heuristic=True),
            "hardware_software_alignment": DeterministicEvaluator("hardware_software_alignment", "hardware_software_alignment", HardwareSoftwareAlignmentEvaluator(), heuristic=True),
            "peripheral_configuration_correctness": DeterministicEvaluator("peripheral_configuration_correctness", "peripheral_configuration_correctness", PeripheralConfigurationCorrectnessEvaluator(), heuristic=True),
            "sensor_actuator_behavior": DeterministicEvaluator("sensor_actuator_behavior", "sensor_actuator_behavior", SensorActuatorBehaviorEvaluator(), heuristic=True),
            "serial_log_behavior_alignment": DeterministicEvaluator("serial_log_behavior_alignment", "serial_log_behavior_alignment", SerialLogBehaviorAlignmentEvaluator(), heuristic=True),
            "state_machine_behavior": DeterministicEvaluator("state_machine_behavior", "state_machine_behavior", StateMachineBehaviorEvaluator(), heuristic=True),
            "plot_interpretation": DeterministicEvaluator("plot_interpretation", "plot_interpretation", PlotInterpretationEvaluator(), heuristic=True, notes="Checks whether plots have axes, labels, and usable curve structure."),
            "observation_sheet_understanding": DeterministicEvaluator("observation_sheet_understanding", "observation_sheet_understanding", ObservationSheetUnderstandingEvaluator(), heuristic=True, notes="Checks observation-table completeness and expected/measured structure."),
            "prompt_relevance": DeterministicEvaluator("prompt_relevance", "prompt_relevance", PromptRelevanceEvaluator(), heuristic=True, notes="Humanities prompt-targeting check."),
            "counterargument_awareness": HybridEvaluator("counterargument_awareness", "counterargument_awareness", CounterargumentAwarenessEvaluator(), LLMArgumentQualityEvaluator(), llm_weight=0.2, notes="Humanities nuance/counterposition check."),
            "source_integration": HybridEvaluator("source_integration", "source_integration", SourceIntegrationEvaluator(), LLMArgumentQualityEvaluator(), llm_weight=0.2, notes="Distinguishes citation from analytical integration."),
            "discourse_structure": DeterministicEvaluator("discourse_structure", "discourse_structure", DiscourseStructureEvaluator(), heuristic=True, notes="Humanities paragraph/transition structure check."),
            "interpretive_depth": HybridEvaluator("interpretive_depth", "interpretive_depth", InterpretiveDepthEvaluator(), LLMArgumentQualityEvaluator(), llm_weight=0.2, notes="Rewards interpretation over mere summary."),
            "llm_subjective_reasoning": LLMEvaluator("llm_subjective_reasoning", "subjective_reasoning", LLMSubjectiveReasoningEvaluator()),
            "llm_argument_quality": LLMEvaluator("llm_argument_quality", "argument_quality", LLMArgumentQualityEvaluator()),
            "llm_proof_explanation": LLMEvaluator("llm_proof_explanation", "proof_explanation", LLMProofExplanationEvaluator()),
            "llm_design_justification": LLMEvaluator("llm_design_justification", "design_justification", LLMDesignJustificationEvaluator()),
            "llm_feedback_synthesizer": LLMEvaluator("llm_feedback_synthesizer", "feedback_synthesis", LLMFeedbackSynthesizerEvaluator()),
        }

    def get(self, evaluator_id: str):
        return self._registry.get(evaluator_id)

    def describe(self) -> dict[str, str]:
        return {name: getattr(ev, "evaluator_type", "unknown") for name, ev in self._registry.items()}
